# Generated by Django 6.0.3 on 2026-03-28 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betrax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='Betrax.defectreport'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate'), ('Assigned', 'Assigned'), ('Fixed', 'Fixed'), ('Reopened', 'Reopened'), ('Resolved', 'Resolved')], default='New', max_length=20),
        ),
    ]
