# Generated by Django 6.0.3 on 2026-04-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betrax', '0002_defectreport_duplicate_of_alter_defectreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='defectreport',
            name='defect_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Betrax.defectreport'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='priority',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='Betrax.product'),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='severity',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('LOW', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('ASSIGNED', 'Assigned'), ('CANNOT_REPRODUCE', 'Cannot Reproduce'), ('FIXED', 'Fixed'), ('REOPENED', 'Reopened'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='tester_email',
            field=models.EmailField(blank=True, default='admin@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='tester_id',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('employeerole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Betrax.employeerole')),
            ],
            bases=('Betrax.employeerole',),
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('employeerole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Betrax.employeerole')),
            ],
            bases=('Betrax.employeerole',),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Betrax.employeerole'),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='Betrax.employeerole')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='Betrax.defectreport')),
            ],
        ),
        migrations.AddField(
            model_name='employeerole',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Betrax.employee'),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AlterField(
            model_name='defectreport',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to='Betrax.developer'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to='Betrax.productowner'),
        ),
    ]
