# Generated by Django 6.0.3 on 2026-04-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betrax', '0003_employeerole_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='defect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Betrax.defectreport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
