# Generated by Django 6.0.3 on 2026-04-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betrax', '0004_alter_comment_defect_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperMetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FIXED', 'Fixed'), ('REOPENED', 'Reopened')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_events', to='Betrax.defectreport')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_events', to='Betrax.developer')),
            ],
        ),
    ]
